### ISSUE TITLE
初步设计的页面

### ISSUE THREAD

**Issue by Kiriseven** [Sys-Lab/MissionOffer#5]
<img width="683" alt="main" src="https://cloud.githubusercontent.com/assets/14849126/10313118/033cd8f6-6c89-11e5-80f8-e6bb179fed84.png">
大家看看然后提提意见吧_(:3 」∠)_

**Comment by langker** [comment]
不错不错，叶家果然厉害，霸占前五名：）

**Comment by langker** [comment]
另外其实设计相关的工作不建议放在 GITHUB 上来做，可以放在 TOWER 里面进行讨论，这样子主要是比较好算设计类的绩效：）））

**Comment by 12wang3** [comment]
我觉得下面的版块之间是不是可以再紧凑一点，现在的空白稍多，还有就是下面版块的配色可以再改一下。

**Comment by Kiriseven** [comment]
> 另外其实设计相关的工作不建议放在 GITHUB 上来做，可以放在 TOWER 里面进行讨论，这样子主要是比较好算设计类的绩效：）））

好的_(:3 」∠)_

**Comment by Kiriseven** [comment]
> 我觉得下面的版块之间是不是可以再紧凑一点，现在的空白稍多，还有就是下面版块的配色可以再改一下。

恩恩，配色具体哪一块不自然？我再想想

**Comment by hsdtlx** [comment]
可以的，不愧梦神。。。不过一片绿感觉有点违和。。

**Comment by Kiriseven** [comment]
> 可以的，不愧梦神。。。不过一片绿感觉有点违和。。

主要我怕颜色杂了会乱起来。。。再去努力研究一下配色好了(｀･ω･´)
